In [64]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/작업형1

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/작업형1

In [65]:
# Section 01 필터링, 최솟값, 중앙값
# 1. 'f5' 컬럼이 0이 아닌 데이터(행)를 구하시오.
# 2. 앞에서 구한 데이터에 'views' 컬럼 결측치를 'views' 컬럼의 최솟값으로 채워주세요.
# 3. 그리고 'views' 컬럼의 중앙값을 계산해 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [66]:
# 1. 'f5' 컬럼이 0이 아닌 데이터(행)를 구하시오.
cond = df['f5'] != 0
df = df[cond]
df

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [67]:
# 2. 앞에서 구한 데이터에 'views' 컬럼 결측치를 'views' 컬럼의 최솟값으로 채워주세요.
min = df['views'].min() # 42.0
df['views'] = df['views'].fillna(min)
# df[df['views'].isnull()] # 결측치가 하나도 없으므로, 최솟값으로 잘 채워진 것임.
df

/tmp/ipykernel_11815/2787375408.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['views'] = df['views'].fillna(min)

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [68]:
# 3. 그리고 'views' 컬럼의 중앙값을 계산해 정수로 구하시오.
mid = df['views'].median() # 5924.0
print(int(mid))

5924

In [69]:
# Section 02 카테고리, 인덱스, 문자열 슬라이싱
# 1. 'subscribed' 컬럼에서 가장 빈도수가 많은 날짜를 구하시오.
# 2. 앞에서 구한 날짜의 일(day) 값을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [70]:
# 1. 'subscribed' 컬럼에서 가장 빈도수가 많은 날짜를 구하시오.
df = df['subscribed'].value_counts() # 2025-02-17
df

subscribed
2025-02-17    16
2024-06-21     3
2024-07-16     2
2024-04-03     2
2024-02-09     2
              ..
2024-05-06     1
2024-10-02     1
2024-12-02     1
2025-01-29     1
2025-01-30     1
Name: count, Length: 96, dtype: int64

In [71]:
# 2. 앞에서 구한 날짜의 일(day) 값을 정수로 구하시오.
print(int(df.index[0][-2:])) # .index[]는 n번째 인덱스를 가져옴

17

In [72]:
# Section 03 파생변수, 정렬, 인덱싱
# 1. 결측치가 있는 데이터(행)를 제거하시오.
# 2. 'views' 컬럼을 'f1' 컬럼으로 나눈 값을 새로운 컬럼으로 추가하시오.
# 3. 새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [73]:
# 1. 결측치가 있는 데이터(행)를 제거하시오.
df = df.dropna()
df

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

In [74]:
# 2. 'views' 컬럼을 'f1' 컬럼으로 나눈 값을 새로운 컬럼으로 추가하시오.
df['new'] = df['views'] / df['f1']
df

/tmp/ipykernel_11815/2938954014.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new'] = df['views'] / df['f1']

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208
...,...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,5628.0,86.584615
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,1267.0,105.583333
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,6543.0,100.661538
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,25.063830

In [75]:
# 3. 새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를 정수로 구하시오.
df.sort_values('new', ascending = False)
print(int(df.iloc[0][1]))

27

/tmp/ipykernel_11815/3695156466.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(int(df.iloc[0][1]))

In [76]:
# Section 04 값 변경, 정렬, 합계
# 1. 'views' 컬럼의 결측 데이터를 0으로 대체하시오.
# 2. 'views' 컬럼에서 상위 10번째 값을 구하시오.
# 3. 'views' 컬럼에서 상위 10개의 값을 상위 10번째 값으로 대체하시오.
# 4. 'views' 컬럼의 전체 합을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [77]:
# 1. 'views' 컬럼의 결측 데이터를 0으로 대체하시오.
# f1, f3, views 결측치 존재
# df.info()
df['views'] = df['views'].fillna(0)

In [78]:
# 2. 'views' 컬럼에서 상위 10번째 값을 구하시오.
df = df.sort_values('views', ascending = False)
num = df.iloc[9]['views']
print(num)

9877.0

In [79]:
# 3. 'views' 컬럼에서 상위 10개의 값을 상위 10번째 값으로 대체하시오.
df.loc[:9, 'views'] = num
df

       id   age city    f1  f2   f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56   id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83   id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32   id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
10  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
..    ...   ...  ...   ...  ..  ...   ...        ...         ...     ...
93   id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07    42.0
48   id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25     0.0
39   id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22     0.0
20   id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16     0.0
82   id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17     0.0

[120 rows x 10 columns]

In [80]:
# 4. 'views' 컬럼의 전체 합을 정수로 구하시오.
print(int(df['views'].sum()))

652812

In [81]:
# Section 05 문자열 슬라이싱, 파생변수, 평균값
# 1. 'f4' 컬럼 데이터에 'FJ'가 포함된 데이터를 찾으시오.
# 2. 찾은 데이터 중에서 'f2' 컬럼의 평균값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [82]:
# 1. 'f4' 컬럼 데이터에 'FJ'가 포함된 데이터를 찾으시오.
df['new'] = df['f4'].str.contains('FJ')
df

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
0,id01,2.0,서울,NaN,0,gold,ENFJ,91.297791,2024-07-16,6820.0,True
1,id02,9.0,서울,70.0,1,NaN,ENFJ,60.339826,2024-05-12,2534.0,True
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,False
3,id04,75.0,서울,NaN,2,NaN,INFP,52.667078,2024-07-21,493.0,False
4,id05,24.0,서울,85.0,2,NaN,ISFJ,29.269869,2024-03-07,1338.0,True
...,...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,False
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,5628.0,False
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,1267.0,False
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,6543.0,False
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,True

In [83]:
# 2. 찾은 데이터 중에서 'f2' 컬럼의 평균값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)
cond = (df['new'] == True)

print(round(df[cond]['f2'].mean(), 2))

0.61

In [84]:
# Section 06 필터링, 분산
# 1. 'f3' 컬럼이 gold이면서 'f2' 컬럼이 2인 데이터를 찾으시오.
# 2. 찾은 데이터에서 'f1' 컬럼의 분산을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [85]:
# 1. 'f3' 컬럼이 gold이면서 'f2' 컬럼이 2인 데이터를 찾으시오.
cond = ((df['f3'] == 'gold') & (df['f2'] == 2))
df = df[cond]
df

        id   age city    f1  f2    f3    f4         f5  subscribed   views
18    id18  41.0   서울  87.0   2  gold  ISFJ  80.138280  2024-03-03  7933.0
29    id29 -13.5   부산  47.0   2  gold  ENTP  67.886373  2024-08-28  6793.0
42    id42  65.0   대구  48.0   2  gold  ESTP  33.308999  2024-02-09  5999.0
55    id55  75.0   대구  63.0   2  gold  ENTP  13.049921  2024-02-06  6042.0
64    id64  43.0   경기  62.0   2  gold  ESFP  73.586397  2024-02-22  5995.0
68    id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
71    id71  35.0   경기  84.0   2  gold  ISFP  52.667078  2024-07-15  8087.0
101   id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
112  id111  22.0   부산  65.0   2  gold  ENTP   0.000000  2025-02-17  7894.0
118  id117  23.0   대구  65.0   2  gold  INFP   0.000000  2025-02-17  6543.0

In [86]:
# 2. 찾은 데이터에서 'f1' 컬럼의 분산을 구하시오. (반올림 후 소수 둘째 자리까지 계산)
print(round(df['f1'].var(), 2))

235.43

In [87]:
# Section 07 값 변경(연산), 필터링 절댓값
# 1. 모든 나이(age)에 1을 더하시오.
# 2. 20대의 'views' 평균과 30대의 'views' 평균의 차이의 절댓값을 구하시오.(반올림 후 소수 둘째 자리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [88]:
# 1. 모든 나이(age)에 1을 더하시오.
df['age'] = df['age'] + 1
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   3.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02  10.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  28.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  76.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  25.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  23.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  24.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  24.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  24.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  25.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [89]:
# 2. 20대의 'views' 평균과 30대의 'views' 평균의 차이의 절댓값을 구하시오.(반올림 후 소수 둘째 자리까지 계산)
cond1 = (df['age'] >= 20) & (df['age'] < 30)
cond2 = (df['age'] >= 30) & (df['age'] < 40)
avg_20 = df[cond1]['views'].mean()
avg_30 = df[cond2]['views'].mean()
avg_abs = avg_20 - avg_30
print(round(abs(avg_abs), 2))

263.13

In [90]:
# Section 08 시계열 데이터, 필터링, 데이터 개수
# 1. 'subscribed' 컬럼이 2024년 2월인 데이터를 찾으시오.
# 2. 위에서 찾은 데이터 중 'f3' 컬럼이 gold인 데이터의 개수를 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [91]:
# 1. 'subscribed' 컬럼이 2024년 2월인 데이터를 찾으시오.
df['subscribed'] = pd.to_datetime(df['subscribed'], format = '%Y-%m-%d')
cond = (df['subscribed'].dt.year == 2024) & (df['subscribed'].dt.month == 2)
df = df[cond]
df

        id   age city    f1  f2      f3    f4         f5 subscribed    views
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0
22    id22  -6.3   부산  72.0   1    gold  ENFP  52.667078 2024-02-09   6147.0
31    id31  86.0   부산  77.0   0    gold  ESFJ  73.586397 2024-02-11   8014.0
34    id34  65.0   부산   NaN   1  silver  INFP  48.431184 2024-02-01   3163.0
42    id42  65.0   대구  48.0   2    gold  ESTP  33.308999 2024-02-09   5999.0
55    id55  75.0   대구  63.0   2    gold  ENTP  13.049921 2024-02-06   6042.0
61    id61  87.0   경기  62.0   2     NaN  INTP  69.730313 2024-02-03    218.0
64    id64  43.0   경기  62.0   2    gold  ESFP  73.586397 2024-02-22   5995.0
86    id86   2.0   경기   NaN   0     NaN  ESTP  29.269869 2024-02-16   2155.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0

In [92]:
# 2. 위에서 찾은 데이터 중 'f3' 컬럼이 gold인 데이터의 개수를 구하시오.
cond = (df['f3'] == 'gold')
print(len(df[cond]))

5

In [93]:
# Section 09 필터링, 카테고리, 최빈값
# 1. 'views' 컬럼 값이 1000 이하인 데이터(결측치 제외)를 찾으시오.
# 2. 앞에서 구한 데이터 중 'f4' 컬럼의 최빈값을 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [94]:
# 1. 'views' 컬럼 값이 1000 이하인 데이터(결측치 제외)를 찾으시오.
cond = (df['views'] <= 1000)
df = df[cond]
df

      id   age city    f1  f2   f3    f4         f5  subscribed  views
3   id04  75.0   서울   NaN   2  NaN  INFP  52.667078  2024-07-21  493.0
6   id07  36.3   서울  60.0   1  NaN  ISFJ   9.796378  2024-01-11   61.0
30  id30  16.0   부산   NaN   0  NaN  ESTJ  17.252986  2024-05-28  240.0
44  id44  44.0   대구   NaN   0  NaN  INTP  16.283854  2024-11-10  546.0
61  id61  87.0   경기  62.0   2  NaN  INTP  69.730313  2024-02-03  218.0
72  id72   8.0   경기  97.0   0  NaN  ESTJ  97.381034  2024-01-30  602.0
73  id73  90.0   경기   NaN   1  NaN  ISFJ  73.586397  2024-08-12  512.0
81  id81  86.0   경기  50.0   1  NaN  ISFJ  37.113739  2024-09-14  244.0
93  id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07   42.0
98  id98  39.0   경기  58.0   2  NaN  INFP  98.429899  2024-10-02  865.0

In [95]:
# 2. 앞에서 구한 데이터 중 'f4' 컬럼의 최빈값을 구하시오.
df = df['f4'].value_counts()
print(df.index[0])

ISFJ

In [96]:
# Section 10 그룹핑, 최댓값, 정렬
# 1. 결측치가 있는 행을 삭제하시오.
# 2. 결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 계산하시오.
# 3. 앞에서 계산한 지역별 평균 데이터에서 'f2' 컬럼 값이 가장 큰 지역을 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [97]:
# 1. 결측치가 있는 행을 삭제하시오.
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 2 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          70 non-null     object
 1   age         70 non-null     float64
 2   city        70 non-null     object
 3   f1          70 non-null     float64
 4   f2          70 non-null     int64
 5   f3          70 non-null     object
 6   f4          70 non-null     object
 7   f5          70 non-null     float64
 8   subscribed  70 non-null     object
 9   views       70 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 6.0+ KB

In [98]:
# 2. 결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 계산하시오.
df = df.groupby('city').mean(numeric_only = True)
df

            age         f1        f2         f5        views
city
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
대구    49.773333  66.200000  0.666667  27.370166  6819.133333
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
서울    38.000000  60.142857  0.785714  41.122705  7369.142857

In [99]:
# 3. 앞에서 계산한 지역별 평균 데이터에서 'f2' 컬럼 값이 가장 큰 지역을 구하시오.
df = df.sort_values('f2', ascending = False)
df.index[0] # df['f2'].idxmax()

'서울'

In [100]:
# Section 11 슬라이싱, 사분위수, 결측치 제거
# 1. 데이터에서 결측치가 있는 데이터(행)를 모두 제거하시오.
# 2. 결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)
# 3. 앞에서 구한 70% 데이터 중 'views' 컬럼의 3사분위수에서 1사분위수를 뺀 값을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [101]:
# 1. 데이터에서 결측치가 있는 데이터(행)를 모두 제거하시오.
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 2 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          70 non-null     object
 1   age         70 non-null     float64
 2   city        70 non-null     object
 3   f1          70 non-null     float64
 4   f2          70 non-null     int64
 5   f3          70 non-null     object
 6   f4          70 non-null     object
 7   f5          70 non-null     float64
 8   subscribed  70 non-null     object
 9   views       70 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 6.0+ KB

In [102]:
# 2. 결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)
seventy_percent = round(len(df)*0.7)
df = df.iloc[:seventy_percent]

In [103]:
# 3. 앞에서 구한 70% 데이터 중 'views' 컬럼의 3사분위수에서 1사분위수를 뺀 값을 정수로 구하시오.
third = df['views'].quantile(0.75)
one = df['views'].quantile(0.25)
print(int(third - one))

2771

In [104]:
# Section 12 결측치 처리, 최빈값, 데이터 개수
# 1. 결측치가 가장 많은 두 컬럼을 찾으시오.
# 2. 첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.
# 3. 두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.
# 4. 'f3' 컬럼의 'gold' 값을 가진 데이터의 수를 정수형으로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [105]:
# 1. 결측치가 가장 많은 두 컬럼을 찾으시오.
print(df.isnull().sum()) # 혹은 df.info()로 찾기

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [106]:
# 2. 첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.
df = df.dropna(subset = ['f1'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 1 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          89 non-null     object
 1   age         89 non-null     float64
 2   city        89 non-null     object
 3   f1          89 non-null     float64
 4   f2          89 non-null     int64
 5   f3          70 non-null     object
 6   f4          89 non-null     object
 7   f5          89 non-null     float64
 8   subscribed  89 non-null     object
 9   views       87 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.6+ KB

In [107]:
# 3. 두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.
mode = df['f3'].mode()[0]
df['f3'] = df['f3'].fillna(mode)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 1 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          89 non-null     object
 1   age         89 non-null     float64
 2   city        89 non-null     object
 3   f1          89 non-null     float64
 4   f2          89 non-null     int64
 5   f3          89 non-null     object
 6   f4          89 non-null     object
 7   f5          89 non-null     float64
 8   subscribed  89 non-null     object
 9   views       87 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.6+ KB

/tmp/ipykernel_11815/2994942574.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['f3'] = df['f3'].fillna(mode)

In [108]:
# 4. 'f3' 컬럼의 'gold' 값을 가진 데이터의 수를 정수형으로 구하시오.
cond = (df['f3'] == 'gold')
print(len(df[cond]))

63

In [117]:
# Section 13 결측 데이터 찾기, 필터링, 평균값
# 1. 'f1' 컬럼에 결측치가 있는 데이터만 선택하시오.
# 2. 선택된 데이터에서 'age' 컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 짜리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [125]:
# 1. 'f1' 컬럼에 결측치가 있는 데이터만 선택하시오.
cond = df['f1'].isna()
df = df[cond]
df

      id    age city  f1  f2      f3    f4         f5  subscribed    views
0   id01    2.0   서울 NaN   0    gold  ENFJ  91.297791  2024-07-16   6820.0
3   id04   75.0   서울 NaN   2     NaN  INFP  52.667078  2024-07-21    493.0
12  id12   20.0   서울 NaN   0     NaN  ESTP  91.297791  2024-11-30   1367.0
17  id17   74.0   서울 NaN   1    gold  ISTP  67.886373  2024-10-26   9441.0
19  id19   53.0   서울 NaN   0    gold  ISFP  83.685380  2024-12-24   5287.0
21  id21   90.0   부산 NaN   1    gold  ISFP  29.269869  2024-05-03   9690.0
25  id25   34.0   부산 NaN   0    gold  ESTP  60.339826  2024-07-12   8954.0
30  id30   16.0   부산 NaN   0     NaN  ESTJ  17.252986  2024-05-28    240.0
34  id34   65.0   부산 NaN   1  silver  INFP  48.431184  2024-02-01   3163.0
35  id35   30.0   부산 NaN   2  silver  ESTJ  33.308999  2024-06-10   3084.0
37  id37  100.0   부산 NaN   0  silver  ESTP  33.308999  2024-07-08   4068.0
38  id38   87.0   부산 NaN   1     NaN  ESTP  83.685380  2024-06-21   1048.0
44  id44   44.0   대구 NaN   0     NaN  INTP  16.283854  2024-11-10    546.0
46  id46   93.0   대구 NaN   0    gold  ESTJ  67.886373  2024-05-23   9711.0
48  id48   18.0   대구 NaN   0     NaN  ENFP  20.129444  2024-03-25      NaN
51  id51   36.0   대구 NaN   0    gold  ISTJ  83.685380  2024-08-20   7217.0
54  id54   53.0   대구 NaN   1    gold  ENFJ  69.730313  2024-06-21   5872.0
56  id56   59.0   대구 NaN   1     vip  ESTJ  73.586397  2024-04-05  19589.0
59  id59   64.0   대구 NaN   1  silver  ESFJ  20.129444  2024-06-23   4994.0
60  id60   56.0   경기 NaN   0    gold  ESFP  52.667078  2024-11-24   6794.0
62  id62   52.0   경기 NaN   0     NaN  INTP  60.339826  2024-04-10   2100.0
65  id65   26.5   경기 NaN   0  silver  ISFP  91.297791  2024-01-10   3336.0
66  id66   87.0   경기 NaN   1    gold  ISFP  17.252986  2024-08-05   8471.0
73  id73   90.0   경기 NaN   1     NaN  ISFJ  73.586397  2024-08-12    512.0
79  id79   30.0   경기 NaN   0    gold  INTJ  80.138280  2024-08-14   8777.0
82  id82   48.0   경기 NaN   0     NaN  ENTJ  37.113739  2024-10-17      NaN
86  id86    2.0   경기 NaN   0     NaN  ESTP  29.269869  2024-02-16   2155.0
87  id87   19.0   경기 NaN   1    gold  ISFP  97.381034  2024-08-30   6516.0
90  id90   54.0   경기 NaN   0  silver  ENTP  29.269869  2024-04-03   3818.0
94  id94   84.0   경기 NaN   1  silver  ESTJ  90.496999  2024-08-16   3774.0
97  id97  100.0   경기 NaN   0    gold  INFP  67.886373  2024-03-18   6687.0

In [130]:
# 2. 선택된 데이터에서 'age' 컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 짜리까지 계산)
print(round(df['age'].mean(), 1))

53.6