In [569]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/작업형1

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/작업형1

In [570]:
# Section 01 필터링, 최솟값, 중앙값
# 1. 'f5' 컬럼이 0이 아닌 데이터(행)를 구하시오.
# 2. 앞에서 구한 데이터에 'views' 컬럼 결측치를 'views' 컬럼의 최솟값으로 채워주세요.
# 3. 그리고 'views' 컬럼의 중앙값을 계산해 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [571]:
# 1. 'f5' 컬럼이 0이 아닌 데이터(행)를 구하시오.
cond = df['f5'] != 0
df = df[cond]
df

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [572]:
# 2. 앞에서 구한 데이터에 'views' 컬럼 결측치를 'views' 컬럼의 최솟값으로 채워주세요.
min = df['views'].min() # 42.0
df['views'] = df['views'].fillna(min)
# df[df['views'].isnull()] # 결측치가 하나도 없으므로, 최솟값으로 잘 채워진 것임.
df

/tmp/ipykernel_11815/2787375408.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['views'] = df['views'].fillna(min)

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [573]:
# 3. 그리고 'views' 컬럼의 중앙값을 계산해 정수로 구하시오.
mid = df['views'].median() # 5924.0
print(int(mid))

5924

In [574]:
# Section 02 카테고리, 인덱스, 문자열 슬라이싱
# 1. 'subscribed' 컬럼에서 가장 빈도수가 많은 날짜를 구하시오.
# 2. 앞에서 구한 날짜의 일(day) 값을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [575]:
# 1. 'subscribed' 컬럼에서 가장 빈도수가 많은 날짜를 구하시오.
df = df['subscribed'].value_counts() # 2025-02-17
df

subscribed
2025-02-17    16
2024-06-21     3
2024-07-16     2
2024-04-03     2
2024-02-09     2
              ..
2024-05-06     1
2024-10-02     1
2024-12-02     1
2025-01-29     1
2025-01-30     1
Name: count, Length: 96, dtype: int64

In [576]:
# 2. 앞에서 구한 날짜의 일(day) 값을 정수로 구하시오.
print(int(df.index[0][-2:])) # .index[]는 n번째 인덱스를 가져옴

17

In [577]:
# Section 03 파생변수, 정렬, 인덱싱
# 1. 결측치가 있는 데이터(행)를 제거하시오.
# 2. 'views' 컬럼을 'f1' 컬럼으로 나눈 값을 새로운 컬럼으로 추가하시오.
# 3. 새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [578]:
# 1. 결측치가 있는 데이터(행)를 제거하시오.
df = df.dropna()
df

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

In [579]:
# 2. 'views' 컬럼을 'f1' 컬럼으로 나눈 값을 새로운 컬럼으로 추가하시오.
df['new'] = df['views'] / df['f1']
df

/tmp/ipykernel_11815/2938954014.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new'] = df['views'] / df['f1']

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208
...,...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,5628.0,86.584615
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,1267.0,105.583333
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,6543.0,100.661538
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,25.063830

In [580]:
# 3. 새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를 정수로 구하시오.
df.sort_values('new', ascending = False)
print(int(df.iloc[0][1]))

27

/tmp/ipykernel_11815/3695156466.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(int(df.iloc[0][1]))

In [581]:
# Section 04 값 변경, 정렬, 합계
# 1. 'views' 컬럼의 결측 데이터를 0으로 대체하시오.
# 2. 'views' 컬럼에서 상위 10번째 값을 구하시오.
# 3. 'views' 컬럼에서 상위 10개의 값을 상위 10번째 값으로 대체하시오.
# 4. 'views' 컬럼의 전체 합을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [582]:
# 1. 'views' 컬럼의 결측 데이터를 0으로 대체하시오.
# f1, f3, views 결측치 존재
# df.info()
df['views'] = df['views'].fillna(0)

In [583]:
# 2. 'views' 컬럼에서 상위 10번째 값을 구하시오.
df = df.sort_values('views', ascending = False)
num = df.iloc[9]['views']
print(num)

9877.0

In [584]:
# 3. 'views' 컬럼에서 상위 10개의 값을 상위 10번째 값으로 대체하시오.
df.loc[:9, 'views'] = num
df

       id   age city    f1  f2   f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56   id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83   id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32   id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
10  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
..    ...   ...  ...   ...  ..  ...   ...        ...         ...     ...
93   id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07    42.0
48   id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25     0.0
39   id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22     0.0
20   id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16     0.0
82   id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17     0.0

[120 rows x 10 columns]

In [585]:
# 4. 'views' 컬럼의 전체 합을 정수로 구하시오.
print(int(df['views'].sum()))

652812

In [586]:
# Section 05 문자열 슬라이싱, 파생변수, 평균값
# 1. 'f4' 컬럼 데이터에 'FJ'가 포함된 데이터를 찾으시오.
# 2. 찾은 데이터 중에서 'f2' 컬럼의 평균값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [587]:
# 1. 'f4' 컬럼 데이터에 'FJ'가 포함된 데이터를 찾으시오.
df['new'] = df['f4'].str.contains('FJ')
df

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
0,id01,2.0,서울,NaN,0,gold,ENFJ,91.297791,2024-07-16,6820.0,True
1,id02,9.0,서울,70.0,1,NaN,ENFJ,60.339826,2024-05-12,2534.0,True
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,False
3,id04,75.0,서울,NaN,2,NaN,INFP,52.667078,2024-07-21,493.0,False
4,id05,24.0,서울,85.0,2,NaN,ISFJ,29.269869,2024-03-07,1338.0,True
...,...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,False
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,5628.0,False
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,1267.0,False
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,6543.0,False
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,True

In [588]:
# 2. 찾은 데이터 중에서 'f2' 컬럼의 평균값을 구하시오. (반올림 후 소수 둘째 자리까지 계산)
cond = (df['new'] == True)

print(round(df[cond]['f2'].mean(), 2))

0.61

In [589]:
# Section 06 필터링, 분산
# 1. 'f3' 컬럼이 gold이면서 'f2' 컬럼이 2인 데이터를 찾으시오.
# 2. 찾은 데이터에서 'f1' 컬럼의 분산을 구하시오. (반올림 후 소수 둘째 자리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [590]:
# 1. 'f3' 컬럼이 gold이면서 'f2' 컬럼이 2인 데이터를 찾으시오.
cond = ((df['f3'] == 'gold') & (df['f2'] == 2))
df = df[cond]
df

        id   age city    f1  f2    f3    f4         f5  subscribed   views
18    id18  41.0   서울  87.0   2  gold  ISFJ  80.138280  2024-03-03  7933.0
29    id29 -13.5   부산  47.0   2  gold  ENTP  67.886373  2024-08-28  6793.0
42    id42  65.0   대구  48.0   2  gold  ESTP  33.308999  2024-02-09  5999.0
55    id55  75.0   대구  63.0   2  gold  ENTP  13.049921  2024-02-06  6042.0
64    id64  43.0   경기  62.0   2  gold  ESFP  73.586397  2024-02-22  5995.0
68    id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
71    id71  35.0   경기  84.0   2  gold  ISFP  52.667078  2024-07-15  8087.0
101   id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
112  id111  22.0   부산  65.0   2  gold  ENTP   0.000000  2025-02-17  7894.0
118  id117  23.0   대구  65.0   2  gold  INFP   0.000000  2025-02-17  6543.0

In [591]:
# 2. 찾은 데이터에서 'f1' 컬럼의 분산을 구하시오. (반올림 후 소수 둘째 자리까지 계산)
print(round(df['f1'].var(), 2))

235.43

In [592]:
# Section 07 값 변경(연산), 필터링 절댓값
# 1. 모든 나이(age)에 1을 더하시오.
# 2. 20대의 'views' 평균과 30대의 'views' 평균의 차이의 절댓값을 구하시오.(반올림 후 소수 둘째 자리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [593]:
# 1. 모든 나이(age)에 1을 더하시오.
df['age'] = df['age'] + 1
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   3.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02  10.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  28.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  76.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  25.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  23.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  24.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  24.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  24.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  25.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [594]:
# 2. 20대의 'views' 평균과 30대의 'views' 평균의 차이의 절댓값을 구하시오.(반올림 후 소수 둘째 자리까지 계산)
cond1 = (df['age'] >= 20) & (df['age'] < 30)
cond2 = (df['age'] >= 30) & (df['age'] < 40)
avg_20 = df[cond1]['views'].mean()
avg_30 = df[cond2]['views'].mean()
avg_abs = avg_20 - avg_30
print(round(abs(avg_abs), 2))

263.13

In [595]:
# Section 08 시계열 데이터, 필터링, 데이터 개수
# 1. 'subscribed' 컬럼이 2024년 2월인 데이터를 찾으시오.
# 2. 위에서 찾은 데이터 중 'f3' 컬럼이 gold인 데이터의 개수를 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [596]:
# 1. 'subscribed' 컬럼이 2024년 2월인 데이터를 찾으시오.
df['subscribed'] = pd.to_datetime(df['subscribed'], format = '%Y-%m-%d')
cond = (df['subscribed'].dt.year == 2024) & (df['subscribed'].dt.month == 2)
df = df[cond]
df

        id   age city    f1  f2      f3    f4         f5 subscribed    views
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0
22    id22  -6.3   부산  72.0   1    gold  ENFP  52.667078 2024-02-09   6147.0
31    id31  86.0   부산  77.0   0    gold  ESFJ  73.586397 2024-02-11   8014.0
34    id34  65.0   부산   NaN   1  silver  INFP  48.431184 2024-02-01   3163.0
42    id42  65.0   대구  48.0   2    gold  ESTP  33.308999 2024-02-09   5999.0
55    id55  75.0   대구  63.0   2    gold  ENTP  13.049921 2024-02-06   6042.0
61    id61  87.0   경기  62.0   2     NaN  INTP  69.730313 2024-02-03    218.0
64    id64  43.0   경기  62.0   2    gold  ESFP  73.586397 2024-02-22   5995.0
86    id86   2.0   경기   NaN   0     NaN  ESTP  29.269869 2024-02-16   2155.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999 2024-02-21  15535.0

In [597]:
# 2. 위에서 찾은 데이터 중 'f3' 컬럼이 gold인 데이터의 개수를 구하시오.
cond = (df['f3'] == 'gold')
print(len(df[cond]))

5

In [598]:
# Section 09 필터링, 카테고리, 최빈값
# 1. 'views' 컬럼 값이 1000 이하인 데이터(결측치 제외)를 찾으시오.
# 2. 앞에서 구한 데이터 중 'f4' 컬럼의 최빈값을 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [599]:
# 1. 'views' 컬럼 값이 1000 이하인 데이터(결측치 제외)를 찾으시오.
cond = (df['views'] <= 1000)
df = df[cond]
df

      id   age city    f1  f2   f3    f4         f5  subscribed  views
3   id04  75.0   서울   NaN   2  NaN  INFP  52.667078  2024-07-21  493.0
6   id07  36.3   서울  60.0   1  NaN  ISFJ   9.796378  2024-01-11   61.0
30  id30  16.0   부산   NaN   0  NaN  ESTJ  17.252986  2024-05-28  240.0
44  id44  44.0   대구   NaN   0  NaN  INTP  16.283854  2024-11-10  546.0
61  id61  87.0   경기  62.0   2  NaN  INTP  69.730313  2024-02-03  218.0
72  id72   8.0   경기  97.0   0  NaN  ESTJ  97.381034  2024-01-30  602.0
73  id73  90.0   경기   NaN   1  NaN  ISFJ  73.586397  2024-08-12  512.0
81  id81  86.0   경기  50.0   1  NaN  ISFJ  37.113739  2024-09-14  244.0
93  id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07   42.0
98  id98  39.0   경기  58.0   2  NaN  INFP  98.429899  2024-10-02  865.0

In [600]:
# 2. 앞에서 구한 데이터 중 'f4' 컬럼의 최빈값을 구하시오.
df = df['f4'].value_counts()
print(df.index[0])

ISFJ

In [601]:
# Section 10 그룹핑, 최댓값, 정렬
# 1. 결측치가 있는 행을 삭제하시오.
# 2. 결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 계산하시오.
# 3. 앞에서 계산한 지역별 평균 데이터에서 'f2' 컬럼 값이 가장 큰 지역을 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [602]:
# 1. 결측치가 있는 행을 삭제하시오.
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 2 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          70 non-null     object
 1   age         70 non-null     float64
 2   city        70 non-null     object
 3   f1          70 non-null     float64
 4   f2          70 non-null     int64
 5   f3          70 non-null     object
 6   f4          70 non-null     object
 7   f5          70 non-null     float64
 8   subscribed  70 non-null     object
 9   views       70 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 6.0+ KB

In [603]:
# 2. 결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 계산하시오.
df = df.groupby('city').mean(numeric_only = True)
df

            age         f1        f2         f5        views
city
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
대구    49.773333  66.200000  0.666667  27.370166  6819.133333
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
서울    38.000000  60.142857  0.785714  41.122705  7369.142857

In [604]:
# 3. 앞에서 계산한 지역별 평균 데이터에서 'f2' 컬럼 값이 가장 큰 지역을 구하시오.
df = df.sort_values('f2', ascending = False)
df.index[0] # df['f2'].idxmax()

'서울'

In [605]:
# Section 11 슬라이싱, 사분위수, 결측치 제거
# 1. 데이터에서 결측치가 있는 데이터(행)를 모두 제거하시오.
# 2. 결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)
# 3. 앞에서 구한 70% 데이터 중 'views' 컬럼의 3사분위수에서 1사분위수를 뺀 값을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [606]:
# 1. 데이터에서 결측치가 있는 데이터(행)를 모두 제거하시오.
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 2 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          70 non-null     object
 1   age         70 non-null     float64
 2   city        70 non-null     object
 3   f1          70 non-null     float64
 4   f2          70 non-null     int64
 5   f3          70 non-null     object
 6   f4          70 non-null     object
 7   f5          70 non-null     float64
 8   subscribed  70 non-null     object
 9   views       70 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 6.0+ KB

In [607]:
# 2. 결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)
seventy_percent = round(len(df)*0.7)
df = df.iloc[:seventy_percent]

In [608]:
# 3. 앞에서 구한 70% 데이터 중 'views' 컬럼의 3사분위수에서 1사분위수를 뺀 값을 정수로 구하시오.
third = df['views'].quantile(0.75)
one = df['views'].quantile(0.25)
print(int(third - one))

2771

In [609]:
# Section 12 결측치 처리, 최빈값, 데이터 개수
# 1. 결측치가 가장 많은 두 컬럼을 찾으시오.
# 2. 첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.
# 3. 두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.
# 4. 'f3' 컬럼의 'gold' 값을 가진 데이터의 수를 정수형으로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [610]:
# 1. 결측치가 가장 많은 두 컬럼을 찾으시오.
print(df.isnull().sum()) # 혹은 df.info()로 찾기

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [611]:
# 2. 첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.
df = df.dropna(subset = ['f1'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 1 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          89 non-null     object
 1   age         89 non-null     float64
 2   city        89 non-null     object
 3   f1          89 non-null     float64
 4   f2          89 non-null     int64
 5   f3          70 non-null     object
 6   f4          89 non-null     object
 7   f5          89 non-null     float64
 8   subscribed  89 non-null     object
 9   views       87 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.6+ KB

In [612]:
# 3. 두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.
mode = df['f3'].mode()[0]
df['f3'] = df['f3'].fillna(mode)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89 entries, 1 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          89 non-null     object
 1   age         89 non-null     float64
 2   city        89 non-null     object
 3   f1          89 non-null     float64
 4   f2          89 non-null     int64
 5   f3          89 non-null     object
 6   f4          89 non-null     object
 7   f5          89 non-null     float64
 8   subscribed  89 non-null     object
 9   views       87 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 7.6+ KB

/tmp/ipykernel_11815/2994942574.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['f3'] = df['f3'].fillna(mode)

In [613]:
# 4. 'f3' 컬럼의 'gold' 값을 가진 데이터의 수를 정수형으로 구하시오.
cond = (df['f3'] == 'gold')
print(len(df[cond]))

63

In [614]:
# Section 13 결측 데이터 찾기, 필터링, 평균값
# 1. 'f1' 컬럼에 결측치가 있는 데이터만 선택하시오.
# 2. 선택된 데이터에서 'age' 컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 짜리까지 계산)

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [615]:
# 1. 'f1' 컬럼에 결측치가 있는 데이터만 선택하시오.
cond = df['f1'].isna()
df = df[cond]
df

      id    age city  f1  f2      f3    f4         f5  subscribed    views
0   id01    2.0   서울 NaN   0    gold  ENFJ  91.297791  2024-07-16   6820.0
3   id04   75.0   서울 NaN   2     NaN  INFP  52.667078  2024-07-21    493.0
12  id12   20.0   서울 NaN   0     NaN  ESTP  91.297791  2024-11-30   1367.0
17  id17   74.0   서울 NaN   1    gold  ISTP  67.886373  2024-10-26   9441.0
19  id19   53.0   서울 NaN   0    gold  ISFP  83.685380  2024-12-24   5287.0
21  id21   90.0   부산 NaN   1    gold  ISFP  29.269869  2024-05-03   9690.0
25  id25   34.0   부산 NaN   0    gold  ESTP  60.339826  2024-07-12   8954.0
30  id30   16.0   부산 NaN   0     NaN  ESTJ  17.252986  2024-05-28    240.0
34  id34   65.0   부산 NaN   1  silver  INFP  48.431184  2024-02-01   3163.0
35  id35   30.0   부산 NaN   2  silver  ESTJ  33.308999  2024-06-10   3084.0
37  id37  100.0   부산 NaN   0  silver  ESTP  33.308999  2024-07-08   4068.0
38  id38   87.0   부산 NaN   1     NaN  ESTP  83.685380  2024-06-21   1048.0
44  id44   44.0   대구 NaN   0     NaN  INTP  16.283854  2024-11-10    546.0
46  id46   93.0   대구 NaN   0    gold  ESTJ  67.886373  2024-05-23   9711.0
48  id48   18.0   대구 NaN   0     NaN  ENFP  20.129444  2024-03-25      NaN
51  id51   36.0   대구 NaN   0    gold  ISTJ  83.685380  2024-08-20   7217.0
54  id54   53.0   대구 NaN   1    gold  ENFJ  69.730313  2024-06-21   5872.0
56  id56   59.0   대구 NaN   1     vip  ESTJ  73.586397  2024-04-05  19589.0
59  id59   64.0   대구 NaN   1  silver  ESFJ  20.129444  2024-06-23   4994.0
60  id60   56.0   경기 NaN   0    gold  ESFP  52.667078  2024-11-24   6794.0
62  id62   52.0   경기 NaN   0     NaN  INTP  60.339826  2024-04-10   2100.0
65  id65   26.5   경기 NaN   0  silver  ISFP  91.297791  2024-01-10   3336.0
66  id66   87.0   경기 NaN   1    gold  ISFP  17.252986  2024-08-05   8471.0
73  id73   90.0   경기 NaN   1     NaN  ISFJ  73.586397  2024-08-12    512.0
79  id79   30.0   경기 NaN   0    gold  INTJ  80.138280  2024-08-14   8777.0
82  id82   48.0   경기 NaN   0     NaN  ENTJ  37.113739  2024-10-17      NaN
86  id86    2.0   경기 NaN   0     NaN  ESTP  29.269869  2024-02-16   2155.0
87  id87   19.0   경기 NaN   1    gold  ISFP  97.381034  2024-08-30   6516.0
90  id90   54.0   경기 NaN   0  silver  ENTP  29.269869  2024-04-03   3818.0
94  id94   84.0   경기 NaN   1  silver  ESTJ  90.496999  2024-08-16   3774.0
97  id97  100.0   경기 NaN   0    gold  INFP  67.886373  2024-03-18   6687.0

In [616]:
# 2. 선택된 데이터에서 'age' 컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 짜리까지 계산)
print(round(df['age'].mean(), 1))

53.6

In [617]:
# Section 14 중복 데이터 제거, 값 변경, 데이터 개수
# 1. 중복 데이터를 제거하시오.
# 2. 'f3' 컬럼의 결측치는 0, 'silver'는 1, 'gold'는 2, 'vip'는 3으로 변환하시오.
# 3. 변환된 'f3' 컬럼의 총합을 정수형으로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [618]:
# 1. 중복 데이터를 제거하시오.
df = df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          118 non-null    object
 1   age         118 non-null    float64
 2   city        118 non-null    object
 3   f1          87 non-null     float64
 4   f2          118 non-null    int64
 5   f3          89 non-null     object
 6   f4          118 non-null    object
 7   f5          118 non-null    float64
 8   subscribed  118 non-null    object
 9   views       114 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 10.1+ KB

In [619]:
# 2. 'f3' 컬럼의 결측치는 0, 'silver'는 1, 'gold'는 2, 'vip'는 3으로 변환하시오.
df['f3'] = df['f3'].fillna(0)
df['f3'] = df['f3'].replace('silver', 1)
df['f3'] = df['f3'].replace('gold', 2)
df['f3'] = df['f3'].replace('vip', 3)
df

/tmp/ipykernel_11815/3781078381.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['f3'] = df['f3'].replace('vip', 3)

        id   age city    f1  f2  f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0   2  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1   0  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1   2  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2   0  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2   0  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..  ..   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0   2  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0   3  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1   1  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2   2  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1   3  ESFJ   0.000000  2025-02-17  2356.0

[118 rows x 10 columns]

In [620]:
# 3. 변환된 'f3' 컬럼의 총합을 정수형으로 구하시오.
print(int(df['f3'].sum()))

167

In [621]:
# Section 15 컬럼 삭제, 행 단위 합계, 필터링
# 1. 주어진 데이터에서 문자 자료형 컬럼을 삭제하시오.
# 2. 숫자 자료형 컬럼의 결측치를 0으로 대체하시오.
# 3. 각 행의 합이 3000보다 큰 값의 개수를 정수로 구하시오. (각 행의 합: 'age' + 'f1' + 'f2' + 'f5' + 'views')

import pandas as pd
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [622]:
# 1. 주어진 데이터에서 문자 자료형 컬럼을 삭제하시오.
df = df.select_dtypes(exclude = 'object')
df

      age    f1  f2         f5   views
0     2.0   NaN   0  91.297791  6820.0
1     9.0  70.0   1  60.339826  2534.0
2    27.0  61.0   1  17.252986  7312.0
3    75.0   NaN   2  52.667078   493.0
4    24.0  85.0   2  29.269869  1338.0
..    ...   ...  ..        ...     ...
115  22.0  23.0   0   0.000000  9747.0
116  23.0  65.0   0   0.000000  5628.0
117  23.0  12.0   1   0.000000  1267.0
118  23.0  65.0   2   0.000000  6543.0
119  24.0  94.0   1   0.000000  2356.0

[120 rows x 5 columns]

In [623]:
# 2. 숫자 자료형 컬럼의 결측치를 0으로 대체하시오.
df = df.fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     120 non-null    float64
 1   f1      120 non-null    float64
 2   f2      120 non-null    int64
 3   f5      120 non-null    float64
 4   views   120 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 4.8 KB

In [624]:
# 3. 각 행의 합이 3000보다 큰 값의 개수를 정수로 구하시오. (각 행의 합: 'age' + 'f1' + 'f2' + 'f5' + 'views')
df = df.T
print(sum(df.sum() > 3000))

88

In [625]:
# Section 16 이상치, IQR
# 1. 'views' 컬럼의 1사분위수, 3사분위수 그리고 IQR을 계산하시오.
# 2. 이상치 조건에 맞는 데이터를 찾으시오. (이상치는 1사분위수 - (IQR + 1.5)보다 작은 값과 3사분위수 + (IQR + 1.5)보다 큰 값)
# 3. 이상치 데이터의 'views' 컬럼 합을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [626]:
# 1. 'views' 컬럼의 1사분위수, 3사분위수 그리고 IQR을 계산하시오.
q1 = df['views'].quantile(0.25)
q3 = df['views'].quantile(0.75)
iqr = q3 - q1
print(iqr)

5442.5

In [627]:
# 2. 이상치 조건에 맞는 데이터를 찾으시오. (이상치는 1사분위수 - (IQR * 1.5)보다 작은 값과 3사분위수 + (IQR * 1.5)보다 큰 값)
cond1 = (q1 - 1.5 * iqr)
cond2 = (q3 + 1.5 * iqr)
cond = (df['views'] < cond1) | (df['views'] > cond2)
df = df[cond]
df

      id   age city    f1  f2   f3    f4         f5  subscribed    views
5   id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  21550.0
32  id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  17421.0
56  id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  19589.0
83  id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  19139.0

In [628]:
# 3. 이상치 데이터의 'views' 컬럼 합을 정수로 구하시오.
print(int(df['views'].sum()))

77699

In [629]:
# Section 17 이상치, 소수점 있는 데이터 찾기, 표준편차
# 1. 'views' 컬럼의 표준편차를 구하시오.
# 2. 'age' 컬럼의 이상치(소수점 나이, 음수 나이, 0살)를 제거하고, 'views' 컬럼의 표준편차를 구하시오.
# 3. 이상치 제거 전후의 'views' 컬럼의 표준편차를 더하여, 반올림 후 소수 둘째 자리까지 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [630]:
# 1. 'views' 컬럼의 표준편차를 구하시오.
before_std = df['views'].std()
print(before_std) # 이상치 제거 전 표준편차

4121.626455600414

In [631]:
# 2. 'age' 컬럼의 이상치(소수점 나이, 음수 나이, 0살)를 제거하고, 'views' 컬럼의 표준편차를 구하시오.
cond = df['age'] > 0
df = df[cond]
cond2 = df['age'] - df['age'].astype(int) == 0
df = df[cond2]
after_std = df['views'].std()
print(after_std)

4175.681776173446

In [632]:
# 3. 이상치 제거 전후의 'views' 컬럼의 표준편차를 더하여, 반올림 후 소수 둘째 자리까지 구하시오.
print(round(before_std + after_std, 2))

8297.31

In [633]:
# Section 18 데이터(행) 기준 평균값, 인덱싱
# 1. index '2001' 데이터(행)에서 평균보다 큰 값의 개수를 구하시오.
# 2. index '2003' 데이터(행)에서 평균보다 작은 값의 개수를 구하시오.
# 3. 두 개수를 더하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data2.csv', index_col='year')
df

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
year,,,,,,,,,,,,,,,,,,,,,
2000,137,74,114,140,80,150,16,133,178,181,...,124,94,118,12,50,191,137,174,56,128
2001,176,87,64,110,128,16,8,4,123,87,...,59,22,3,108,17,104,101,161,156,43
2002,128,132,123,112,134,160,180,47,115,155,...,160,111,116,75,48,51,81,101,194,73
2003,78,45,26,50,177,119,47,72,163,125,...,163,88,52,79,192,83,5,75,196,119
2004,1,162,124,12,1,126,58,123,186,161,...,100,93,86,12,115,72,29,30,88,150

In [634]:
# 1. index '2001' 데이터(행)에서 평균보다 큰 값의 개수를 구하시오.
mean = df.loc[2001].mean()
cond = df.loc[2001] > mean
result1 = cond.sum()
print(result1)

100

In [635]:
# 2. index '2003' 데이터(행)에서 평균보다 작은 값의 개수를 구하시오.
mean = df.loc[2003].mean()
cond = df.loc[2003] < mean
result2 = cond.sum()
print(result2)

102

In [636]:
# 3. 두 개수를 더하시오.
print(result1 + result2)

202

In [637]:
# Section 19 결측치(뒤의 값으로 대체), 그룹합
# 1. 결측치를 바로 뒤에 있는 값으로 대체하시오. (바로 뒤의 값도 결측치일 경우, 뒤에 있는 데이터 중 가장 가까운 값으로 대체)
# 2. 'city'와 'f2' 컬럼을 기준으로 그룹합을 계산하시오.
# 3. 'views' 값이 세 번째로 큰 city 이름을 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [638]:
# 1. 결측치를 바로 뒤에 있는 값으로 대체하시오. (바로 뒤의 값도 결측치일 경우, 뒤에 있는 데이터 중 가장 가까운 값으로 대체)
df = df.fillna(method = 'bfill')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          120 non-null    float64
 4   f2          120 non-null    int64
 5   f3          120 non-null    object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       120 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

/tmp/ipykernel_11815/3953748046.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = 'bfill')

In [639]:
# 2. 'city'와 'f2' 컬럼을 기준으로 그룹합을 계산하시오.
df = df.groupby(['city', 'f2']).sum(numeric_only = True).reset_index()
df

   city  f2     age      f1           f5     views
0    경기   0  1192.9  1490.0  1425.236647  154066.0
1    경기   1   997.0  1016.0   935.958628   91442.0
2    경기   2   296.0   390.0   430.186433   42709.0
3    대구   0   664.0   982.0   371.184620  100421.0
4    대구   1   393.6   471.0   404.779978   49536.0
5    대구   2   185.0   321.0    79.667919   22624.0
6    부산   0   525.0   691.0   395.272907   80460.0
7    부산   1   475.7   684.0   460.657406   51624.0
8    부산   2    38.5   189.0   101.195372   17771.0
9    서울   0   241.0   480.0   484.809540   61447.0
10   서울   1   433.3   687.0   506.371383   59111.0
11   서울   2   165.3   337.0   179.328213   22405.0

In [640]:
# 3. 'views' 값이 세 번째로 큰 city 이름을 구하시오.
df = df.sort_values('views', ascending = False)
print(df.iloc[2, 0])

경기

In [641]:
# Section 20 시계열 데이터, 월별 집계, 인덱스
# 1. 연도 구분 없이 월별로 숫자형 컬럼의 합을 구하시오.
# 2. 합계 중 'views'가 가장 작은 값을 가진 월을 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('type1_data1.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [642]:
# 1. 연도 구분 없이 월별로 숫자형 컬럼의 합을 구하시오.
df['subscribed'] = pd.to_datetime(df['subscribed'])
df['month'] = df['subscribed'].dt.month
df = df.groupby(['month']).sum(numeric_only = True)
df

         age      f1  f2          f5     views
month
1      441.8   608.0   1  487.453162   40013.0
2      860.7  1301.0  25  460.248156  165852.0
3      326.3   457.0   8  352.729057   39031.0
4      307.0   268.0   4  312.187975   41307.0
5      809.6   822.0  10  855.287894  110786.0
6      481.8   244.0   6  387.206296   31295.0
7      534.0   399.0  10  630.370464   67677.0
8      338.5   119.0   6  520.223827   51048.0
9      473.6   356.0   3  379.121958   66340.0
10     483.0   437.0   6  595.737639   48705.0
11     186.0   181.0   1  278.410220   15857.0
12     365.0   373.0   2  515.672397   28658.0

In [650]:
# 2. 합계 중 'views'가 가장 작은 값을 가진 월을 정수로 구하시오.
df = df.sort_values('views', ascending = True)
print(int(df.index[0]))

11

In [652]:
# Section 21 시간 간의 차이 계산(분), 필터링
# 1. 예상 도착 시간보다 늦게 도착한 건수를 구하시오.
# 2. 이 중 거리가 7km 이상인 데이터의 수를 정수로 구하시오.

# 기본 코드
import pandas as pd
df = pd.read_csv('delivery_time.csv')
df

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176
...,...,...,...,...,...,...,...
995,2022-10-10 03:13:30,2022-10-10 04:13:48,2022-10-10 04:15:37,배고팡,1.79,현금,user_186
996,2023-02-03 12:47:19,2023-02-03 13:11:46,2023-02-03 13:12:57,배고팡,15.55,카드,user_239
997,2023-01-05 21:28:58,2023-01-05 21:57:41,2023-01-05 21:57:44,배고팡,8.33,현금,user_264
998,2023-06-15 03:56:42,2023-06-15 04:14:24,2023-06-15 04:18:38,여기여,8.20,앱결제,user_229
999,2023-08-02 20:53:53,2023-08-02 22:04:06,2023-08-02 22:09:22,여기여,5.33,카드,user_148

In [660]:
# 1. 예상 도착 시간보다 늦게 도착한 건수를 구하시오.
df['실제도착시간'] = pd.to_datetime(df['실제도착시간'])
df['예상도착시간'] = pd.to_datetime(df['예상도착시간'])
cond = df['실제도착시간'] > df['예상도착시간']
df = df[cond]
print(len(df))

510

In [663]:
# 2. 이 중 거리가 7km 이상인 데이터의 수를 정수로 구하시오.
cond = df['거리'] >= 7
df = df[cond]
print(len(df))

311