In [1]:
import pandas as pd

# 판다스의 데이터는 시리즈와 데이터프레임으로 구성되어 있음.
# 시리즈는 1차원 형태, 데이터프레임은 행과 열이 있는 2차원 형태

In [10]:
# pd.Series(): 리스트를 만들고 감싸기
menu = pd.Series(['비빔밥', '김치찌개', '된장찌개'])

# object형은 문자열 데이터를 나타내는 데 사용됨.
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [7]:
price = pd.Series([10000, 9000, 8000])

price

0    10000
1     9000
2     8000
dtype: int64

In [15]:
# 앞서 만든 2개의 시리즈를 합쳐 데이터프레임(행렬)로 만들기
pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

df = pd.DataFrame({
    "메뉴" : ["비빔밥", "김치찌개", "된장찌개"],
    "가격" : [10000, 9000, 8000],
    "원산지" : ["국내산", "국내산", "국내산"]
})

df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [29]:
# 시리즈 형태

df['메뉴']
# df.메뉴


# 데이터프레임 형태
df[['메뉴']]


# df[['메뉴', '가격']]와 같음
cols = ['메뉴', '가격']
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [32]:
print("df : ", type(df))
print("df['가격'] : ", type(df['가격']))
print("df[['가격']] : ", type(df[['가격']]))

df :  <class 'pandas.core.frame.DataFrame'>
df['가격'] :  <class 'pandas.core.series.Series'>
df[['가격']] :  <class 'pandas.core.frame.DataFrame'>