In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "메뉴" : ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레스", "밀크티", "녹차"],
    "가격" : [4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리" : [10, 110, 250, 110, 20, 210, 0]
})

df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레스  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

# csv로 저장
df.to_csv('02.데이터 저장 및 불러오기_temp.csv')

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [ ]:
# csv 불러오기
temp_df = pd.read_csv('02.데이터 저장 및 불러오기_temp.csv')
temp_df.head() # 기본 5줄

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레스  4000   20

In [ ]:
# 기존 인덱스 제외하고 csv 저장(Unnamed:0이 없어짐)
df.to_csv('02.데이터 저장 및 불러오기_cafe.csv', index=False)
df = pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv')
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레스  4000   20

In [ ]:
# 인덱스로 사용할 컬럼명 또는 열의 번호 지정
pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', index_col='칼로리')
pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', index_col=2)

        메뉴    가격
칼로리
10   아메리카노  4500
110   카페라떼  5000
250   카페모카  5500
110   카푸치노  5000
20   에스프레스  4000
210    밀크티  5900
0       녹차  5300

In [ ]:
# 불러올 컬럼명 또는 열의 번호 지정
pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', usecols=['메뉴', '가격'])
pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', usecols=[0, 1])

      메뉴    가격
0  아메리카노  4500
1   카페라떼  5000
2   카페모카  5500
3   카푸치노  5000
4  에스프레스  4000
5    밀크티  5900
6     녹차  5300

In [29]:
# 문자열로 된 컬럼을 날짜 datetime으로 변경(파싱)
pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', parse_dates=['메뉴'])

/tmp/ipykernel_3632/567241936.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', parse_dates=['메뉴'])

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레스  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [31]:
pd.read_csv('02.데이터 저장 및 불러오기_cafe.csv', encoding='utf-8')

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 9: illegal multibyte sequence