In [4]:
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [5]:
import pandas as pd

df = pd.DataFrame({
    "메뉴" : ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레스", "밀크티", "녹차"],
    "가격" : [4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리" : [10, 110, 250, 110, 20, 210, 0]
})

df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레스  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [6]:
# 상위 N개의 행 반환
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

In [8]:
# 하위 N개의 행 반환
df.tail(4)

      메뉴    가격  칼로리
3   카푸치노  5000  110
4  에스프레스  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [17]:
# 샘플링(데이터프레임에서 임의로 샘플링해 N개의 행 반환)
df.sample(3)

     메뉴    가격  칼로리
3  카푸치노  5000  110
6    녹차  5300    0
5   밀크티  5900  210

In [18]:
# 데이터프레임의 크기 확인
df.shape

(7, 3)

In [19]:
# 데이터프레임 안 컬럼의 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [20]:
# 상관 관계 확인
# 값 범위: -1 ~ 1
# 1 → 완벽한 양의 상관 (같이 증가)
# -1 → 완벽한 음의 상관 (하나는 증가, 하나는 감소)
# 0 → 관계 없음
# numeric_only: 문자형 컬럼으로 인한 convert 에러 방지
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [31]:
df_car = pd.DataFrame({
"car":['Sedan', 'SUV', 'Sedan', 'SUV','SUV','SUV','Sedan', 'Sedan', 'Sedan', 'Sedan', 'Sedan'],
"size": ['S','M','S','S','M', 'M','L','S','S', 'M','S']
} )

df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [36]:
# unique(): 시리즈에서 고유한 값
df_car['car'].unique()

# nunique(): 시리즈에서 고유한 값 개수
df_car['car'].nunique()

2

In [32]:
# nunique(): number of unique로, 고유한 값의 개수
df_car.nunique()

car     2
size    3
dtype: int64

In [38]:
# value_counts(): unique()와 nuique()의 결과 내용을 한 번에 확인
print(df_car['car'].value_counts())
print()
print(df_car['size'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64

size
S    6
M    4
L    1
Name: count, dtype: int64

In [41]:
# describe(): 수치형 데이터에 대한 기술통계량
# count: 값이 있는 데이터 수, mean: 평균, std: 표준편차, min: 최솟값, 00%: 백분위수에서 00%, max: 최댓값
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [44]:
# describe(include="O"): 범주형(object 자료형) 데이터에 대한 기술통계량
# count: 값이 있는 데이터 수, unique: 고유한 데이터의 수(종류), top: 가장 많이 나오는 값(최빈값), freq: 가장 많이 나오는 값의 빈도 수
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [45]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [47]:
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1