In [2]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [5]:
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [8]:
# 새로운 컬럼명 추가 및 0으로 초기화
df['new'] = 0
df.head(2)

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0

In [9]:
# 기존의 '가격' 컬럼에 20% 할인을 적용하여 '할인가' 컬럼을 새로 만듬.
discount = 0.2
df['할인가'] = df['가격'] * (1 - discount)
df.head(2)

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0