In [22]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [23]:
df = pd.read_csv('cafe.csv')
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

In [24]:
# drop(): 행 혹은 열 삭제
# axis=0: 행, axis=1: 열
# inplace 파라미터를 사용해야 삭제된 결과값이 저장됨. 혹은 inplace대신 '='으로 저장
df.drop(1, axis=0, inplace=True)
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110

In [25]:
df = df.drop('칼로리', axis=1)
df.head(3)

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000

In [27]:
# 실수 방지를 위해 삭제 전후의 데이터 크기를 df.shape로 확인
df.shape # (6, 2)
df = df.drop(3, axis=0)
df.shape # (5, 2)

(5, 2)