In [2]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [3]:
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [13]:
# loc: location의 약자로, 인덱스명 또는 컬럼명을 통해 데이터에 접근
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [14]:
# 0번째 행의 가격
df.loc[0, "가격"]

np.int64(4500)

In [15]:
# location을 활용한 슬라이싱
# 전체 데이터 중, 가격
df.loc[:, "가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [19]:
# 0번째 행의 열들 중에서 메뉴부터 칼로리 사이의 열 출력
df.loc[0, '메뉴':'칼로리']

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [21]:
# 0번째 행의 열들 중에서 특정 열 출력
df.loc[0, ['메뉴', '칼로리']]

메뉴     아메리카노
칼로리       10
Name: 0, dtype: object

In [22]:
df.loc[0:2, '메뉴':'가격']

      메뉴    가격
0  아메리카노  4500
1   카페라떼  5000
2   카페모카  5500