In [2]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [4]:
df = pd.read_csv('cafe.csv')
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레스  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [5]:
df.drop(0, axis=0, inplace=True)
df.head(2)

     메뉴    가격  칼로리
1  카페라떼  5000  110
2  카페모카  5500  250

In [6]:
# iloc: integer location
df.iloc[0]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [12]:
#df.loc[1, '메뉴']
df.iloc[0, 0]

'카페라떼'

In [13]:
df.iloc[:, 1]

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [16]:
df.iloc[2, 0:2]

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [17]:
df

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레스  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [18]:
df.iloc[1:3, :]

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [19]:
df.loc[2:3, '메뉴':'칼로리']

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110