In [1]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [2]:
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [3]:
# 넘파이를 활용하여 결측지(NaN)가 있는 데이터 생성
import numpy as np
df['원산지'] = np.nan
df

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN
4  에스프레스  4000   20  NaN
5    밀크티  5900  210  NaN
6     녹차  5300    0  NaN

In [4]:
df.loc[0, "원산지"] = '콜롬비아'
df.loc[2:3, "원산지"] = '과테말라'
df.head(4)

/tmp/ipykernel_8685/2880772820.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "원산지"] = '콜롬비아'

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라

In [5]:
df.loc['시즌'] = ['크리스마스라떼', 6000, 300, '한국']
df

         메뉴    가격  칼로리   원산지
0     아메리카노  4500   10  콜롬비아
1      카페라떼  5000  110   NaN
2      카페모카  5500  250  과테말라
3      카푸치노  5000  110  과테말라
4     에스프레스  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
시즌  크리스마스라떼  6000  300    한국

In [6]:
# 인덱스명 7로 딕셔너리 형태로 행 추가. 원산지 컬럼은 지정하지 않았기 때문에 결측치인 NaN으로 채워짐.
df.loc[7] = {"메뉴" : "딴짓커피", "가격" : 2000, "칼로리" : 20}
df

         메뉴    가격  칼로리   원산지
0     아메리카노  4500   10  콜롬비아
1      카페라떼  5000  110   NaN
2      카페모카  5500  250  과테말라
3      카푸치노  5000  110  과테말라
4     에스프레스  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
시즌  크리스마스라떼  6000  300    한국
7      딴짓커피  2000   20   NaN

In [7]:
df = df.drop("시즌", axis=0)
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레스  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [8]:
df.to_csv('cafe2.csv', index=False)