In [22]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [23]:
df = pd.read_csv('cafe2.csv')
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레스  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [24]:
# sort_index(): 인덱스 기준 정렬
df.sort_index(ascending=False)

      메뉴    가격  칼로리   원산지
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN
5    밀크티  5900  210   NaN
4  에스프레스  4000   20   NaN
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
0  아메리카노  4500   10  콜롬비아

In [25]:
# sort_values(): 데이터 값 기준 정렬
df.sort_values('메뉴', ascending=False)

      메뉴    가격  칼로리   원산지
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
4  에스프레스  4000   20   NaN
0  아메리카노  4500   10  콜롬비아
5    밀크티  5900  210   NaN
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN

In [26]:
# 가격 내림차순, 메뉴 오름차순(= 가격 DESC, 메뉴 ASC)
df = df.sort_values(['가격', '메뉴'], ascending=[False, True])

In [27]:
df

      메뉴    가격  칼로리   원산지
5    밀크티  5900  210   NaN
2   카페모카  5500  250  과테말라
6     녹차  5300    0   NaN
1   카페라떼  5000  110   NaN
3   카푸치노  5000  110  과테말라
0  아메리카노  4500   10  콜롬비아
4  에스프레스  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [30]:
# df의 인덱스명 순서가 변경되었으므로, 다시 0부터 7까지 새롭게 지정
df.reset_index(drop=True)

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레스  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [31]:
df = df.reset_index(drop=True)

In [32]:
df

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레스  4000   20   NaN
7   딴짓커피  2000   20   NaN