In [1]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [2]:
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [3]:
# < 연산자: 칼로리 컬럼의 각 값이 50보다 작은지
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [7]:
# < 연산자: 칼로리 컬럼의 각 값이 50보다 작은지
df['칼로리'] < 50
# True로 표시된 행들만 선택
df[cond] # df[df['칼로리'] < 50]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레스  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [8]:
# ~: NOT연산자
df[~cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [11]:
# & 연산자: AND 연산이며, 가격이 5000원 이상이면서 칼로리가 100보다 큰 데이터 필터링
cond1 = (df['가격'] >= 5000)
cond2 = (df['칼로리'] > 100)
df[cond1 & cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [12]:
# | 연산자: OR 연산이며, 가격이 5000원 이상이거나 칼로리가 100보다 큰 데이터 필터링
cond1 = (df['가격'] >= 5000)
cond2 = (df['칼로리'] > 100)
df[cond1 | cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN
6    녹차  5300    0   NaN

In [13]:
cond = (df['원산지'] == '과테말라')
df[cond]

     메뉴    가격  칼로리   원산지
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라

In [14]:
cond1 = (df['원산지'] == '과테말라')
cond2 = (df['가격'] <= 5000)
df[cond1 & cond2]

     메뉴    가격  칼로리   원산지
3  카푸치노  5000  110  과테말라

In [19]:
# isin(): 주어진 값이 있는지 확인
cond = df['메뉴'].isin(['녹차'])
df[cond]

   메뉴    가격  칼로리  원산지
6  녹차  5300    0  NaN

In [20]:
box = ['녹차', '카푸치노', '카페라떼']
cond = df['메뉴'].isin(box)
df[cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
3  카푸치노  5000  110  과테말라
6    녹차  5300    0   NaN