In [19]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [20]:
df = pd.read_csv("cafe2.csv")
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [21]:
# 결측치 확인(결측치면 True)
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [22]:
# 결측치이면 1이기 때문에 결측치의 갯수만큼 나옴
df.isnull().sum() # df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [23]:
df.isna().sum() # df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [24]:
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레스  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [25]:
# fillna(): 결측치를 임의의 값으로 채움.
# '원산지' 컬럼에 있는 결측치를 '코스타리카'로 채움.
df['원산지'] = df['원산지'].fillna('코스타리카')
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레스  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [26]:
df.to_csv("cafe3.csv", index=False)