In [1]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [2]:
df = pd.read_csv("cafe3.csv")
df.head(3)

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라

In [3]:
# replace(): 특정 값을 찾아 대체하는 함수. 변경 전 값과 변경 후 값을 입력함.
df.replace('아메리카노', '룽고', inplace=True)
df.replace('녹차',  '그린티', inplace=True)
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레스  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [4]:
# 딕셔너리 기반 replace
change = {'룽고':'아메리카노', '그린티':'녹차'}
df.replace(change, inplace=True)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레스  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [5]:
df.loc[6, '원산지'] = '대한민국'
df.tail(3)

     메뉴    가격  칼로리    원산지
5   밀크티  5900  210  코스타리카
6    녹차  5300    0   대한민국
7  딴짓커피  2000   20  코스타리카

In [6]:
df.loc[1:2, '이벤트가'] = 1000
df.head()

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레스  4000   20  코스타리카     NaN

In [7]:
df.to_csv("cafe4.csv", index=False)

In [8]:
# map(): replace()에 비해 유연성이 뛰어남. map()에서 없는 값이면 nan이 되지만, replace()에서 없는 값이면 기존 값이 유지됨.
df = pd.DataFrame({'만족도' : ['만족', '보통', '불만', '보통', '만족']})

mapping = {'만족' : 3, '보통' : 2, '불만' : 1}
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3