In [1]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [2]:
df = pd.DataFrame({
    'A' : ['데이터 분석', '기본 학습서', '퇴근 후 열공'],
    'B' : [10, 20, 30],
    'C' : ['ab cd', 'AB CD', 'ab cd ']
})
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [4]:
# 단어의 일부분은 변경할 수 없음
df['A'] = df['A'].replace('분석', '시각화')
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [5]:
# str.replace(): str 접근자를 활용하여 전체 문자열 중 일부만 변경
df['A'] = df['A'].str.replace('분석', '시각화')
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [6]:
df['B'] = df['B'].replace(10, 100)
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [7]:
# int형 정수에 str.replace()를 사용하면 에러 발생
df['B'] = df['B'].str.replace(20, 200)
df

AttributeError: Can only use .str accessor with string values!

In [9]:
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [10]:
# str.split(): 문자열 분리
# 문자열을 리스트로 나눠 시리즈 자료형으로 반환
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [11]:
# 특정 행의 데이터 분리
df['A'].str.split()[0]

['데이터', '시각화']

In [13]:
# str.split().str[0]: 분리 후 첫 번째 단어
df['D'] = df['A'].str.split().str[0]
df

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [14]:
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [16]:
# str.contains(): 특정 단어가 포함되어 있는지 확인
# isin()은 값을 찾고, contains()는 값을 찾거나 값의 일부를 찾음.
# isin()은 여러 개의 값을 찾을 수 있는 장점이 있어 필터링에서 유용하게 사용되지만, 1개 값만 찾더라도 .isin(['맛난버거'])와 같이 대괄호 필요
# str.contains()는 문장 속에서 특정 문자열을 찾을 수 있는 장점이 있으며, 리스트 형태가 아니므로 대괄호는 필요 없음.
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B       C    D  기본포함유무
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [19]:
print(df['A'].isin(['기본']))
print(df['A'].str.contains('기본'))

0    False
1    False
2    False
Name: A, dtype: bool
0    False
1     True
2    False
Name: A, dtype: bool

In [20]:
# str.len(): 문자열 길이
df['문자길이'] = df['A'].str.len()
df

         A    B       C    D  기본포함유무  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [21]:
# 대문자 -> 소문자
df['C'] = df['C'].str.lower()
df['C']

0     ab cd
1     ab cd
2    ab cd
Name: C, dtype: object

In [22]:
# 소문자 -> 대문자
df['C'] = df['C'].str.upper()
df['C']

0     AB CD
1     AB CD
2    AB CD
Name: C, dtype: object

In [23]:
df['C'] == 'AB'

0     True
1     True
2    False
Name: C, dtype: bool

In [25]:
# 소문자로 변환 후 공백 제거
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(" ", "")
df['C']

0    abcd
1    abcd
2    abcd
Name: C, dtype: object

In [ ]:
df['C'].str.strip() # 양쪽 공백 제거
df['C'].str.lstrip() # 왼쪽 공백 제거
df['C'].str.rstrip() # 오른쪽 공백 제거

In [26]:
# 'abcd'에서 'bc'
df['C'].str[1:3]

0    bc
1    bc
2    bc
Name: C, dtype: object

In [27]:
df['C'][1:3]

1    abcd
2    abcd
Name: C, dtype: object