In [2]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas
/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [33]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [34]:
# 행의 수
print(len(df))
# 행의 수, 열의 수
print(df.shape[0], df.shape[1])

8
8 5

In [35]:
cond = df['가격'] > 5000

# sum으로 조건에 맞는 개수 구하기
print(sum(cond))
# len으로 조건에 맞는 개수 구하기
print(len(df[cond]))

3
3

In [36]:
df.sum(numeric_only=True)

가격      37200.0
칼로리       730.0
이벤트가     2000.0
dtype: float64

In [37]:
# 행과 열을 서로 변경
df.T

          0       1       2     3      4      5     6      7
메뉴    아메리카노    카페라떼    카페모카  카푸치노  에스프레스    밀크티    녹차   딴짓커피
가격     4500    5000    5500  5000   4000   5900  5300   2000
칼로리      10     110     250   110     20    210     0     20
원산지    콜롬비아   코스타리카    과테말라  과테말라  코스타리카  코스타리카  대한민국  코스타리카
이벤트가    NaN  1000.0  1000.0   NaN    NaN    NaN   NaN    NaN

In [41]:
# 열별 합계
df.sum(numeric_only=True) # df.sum(axis=0, numeric_only=True)
# 행별 합계
# axis=1: 행, axis=0: 열
# drop과 축설정이 반대
df.sum(axis=1, numeric_only=True)

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    2020.0
dtype: float64

In [43]:
# max(), min(), mean(), median(), sum(), std(), var()
print("최댓값: ", df['가격'].max())
print("최솟값: ", df['가격'].min())
print("평균값: ", df['가격'].mean())
print("중앙값: ", df['가격'].median())
print("합계: ", df['가격'].sum())
print("표준편차: ", df['가격'].std())
print("분산: ", df['가격'].var())

최댓값:  5900
최솟값:  2000
평균값:  4650.0
중앙값:  5000.0
합계:  37200
표준편차:  1220.070255588353
분산:  1488571.4285714286

In [71]:
# quantile(): 분위 수 구하기
print("분위수 25% 값:", df['가격'].quantile(.25))
print("분위수 75% 값:", df['가격'].quantile(0.75))

분위수 25% 값: 4375.0
분위수 75% 값: 5350.0

In [48]:
# 1사분위수보다 작은 가격의 데이터 출력
cond = df['가격'].quantile(.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
4  에스프레스  4000   20  코스타리카   NaN
7   딴짓커피  2000   20  코스타리카   NaN

In [49]:
# 3사분위수보다 큰 가격의 데이터 출력
third_quantile = df['가격'].quantile(0.75)
cond = df['가격'] > third_quantile
df[cond]

     메뉴    가격  칼로리    원산지    이벤트가
2  카페모카  5500  250   과테말라  1000.0
5   밀크티  5900  210  코스타리카     NaN

In [52]:
# mode(): 최빈값
# 최빈값은 여러 개일 수도 있으므로, 시리즈 형태로 반환됨. 따라서 인덱스로 원하는 값을 꺼내와야 함.
df['원산지'].mode()[0]

'코스타리카'

In [63]:
# idxmax(): 열에서 최댓값을 갖는 인덱스 반환
# idxmin(): 열에서 최솟값을 갖는 인덱스 반환
print('가격이 가장 큰 인덱스와 가격:', df['가격'].idxmax(), df['가격'].max())
print('가격이 가장 작은 인덱스와 가격:', df['가격'].idxmin(), df['가격'].min())

max_idx = df['가격'].idxmax()
df.loc[max_idx]

가격이 가장 큰 인덱스와 가격: 5 5900
가격이 가장 작은 인덱스와 가격: 7 2000

메뉴        밀크티
가격       5900
칼로리       210
원산지     코스타리카
이벤트가      NaN
Name: 5, dtype: object

In [66]:
# 효율적
print(df.loc[max_idx, '메뉴'])
# 비효율적
print(df.loc[max_idx]['메뉴'])

밀크티
밀크티

In [67]:
# nlargest(): 데이터프레임의 특정 컬럼 중에 큰 값 순으로 n개 반환
df.nlargest(3, '가격')

     메뉴    가격  칼로리    원산지    이벤트가
5   밀크티  5900  210  코스타리카     NaN
2  카페모카  5500  250   과테말라  1000.0
6    녹차  5300    0   대한민국     NaN

In [69]:
# nsmallest(): 데이터프레임의 특정 컬럼 중에 작은 값 순으로 n개 반환
df.nsmallest(2, '가격')

      메뉴    가격  칼로리    원산지  이벤트가
7   딴짓커피  2000   20  코스타리카   NaN
4  에스프레스  4000   20  코스타리카   NaN

In [70]:
# apply(): 적용할 함수명을 인자로 줄 수 있음
def cal(x):
  if x >= 100:
    return "No"
  else:
    return "Yes"

df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

      메뉴    가격  칼로리    원산지    이벤트가 먹어도 될까요
0  아메리카노  4500   10   콜롬비아     NaN     Yes
1   카페라떼  5000  110  코스타리카  1000.0      No
2   카페모카  5500  250   과테말라  1000.0      No
3   카푸치노  5000  110   과테말라     NaN      No
4  에스프레스  4000   20  코스타리카     NaN     Yes
5    밀크티  5900  210  코스타리카     NaN      No
6     녹차  5300    0   대한민국     NaN     Yes
7   딴짓커피  2000   20  코스타리카     NaN     Yes