In [51]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [52]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [53]:
# groupby(): 그룹핑을 수행하는 함수이며, 일반적으로 대괄호는 2개 이상일 때 사용함.
df.groupby('원산지').mean(numeric_only=True)

           가격    칼로리    이벤트가
원산지
과테말라   5250.0  180.0  1000.0
대한민국   5300.0    0.0     NaN
코스타리카  4225.0   90.0  1000.0
콜롬비아   4500.0   10.0     NaN

In [54]:
df.groupby(['원산지', '칼로리']).mean(numeric_only=True)

               가격    이벤트가
원산지   칼로리
과테말라  110  5000.0     NaN
      250  5500.0  1000.0
대한민국  0    5300.0     NaN
코스타리카 20   3000.0     NaN
      110  5000.0  1000.0
      210  5900.0     NaN
콜롬비아  10   4500.0     NaN

In [55]:
# agg(): 여러 개의 컬럼에 대해 다양한 집계 연산 동시 수행
df.groupby(['원산지', '메뉴']).agg(['mean', 'sum'])

                 가격          칼로리         이벤트가
               mean   sum   mean  sum    mean     sum
원산지   메뉴
과테말라  카페모카   5500.0  5500  250.0  250  1000.0  1000.0
      카푸치노   5000.0  5000  110.0  110     NaN     0.0
대한민국  녹차     5300.0  5300    0.0    0     NaN     0.0
코스타리카 딴짓커피   2000.0  2000   20.0   20     NaN     0.0
      밀크티    5900.0  5900  210.0  210     NaN     0.0
      에스프레스  4000.0  4000   20.0   20     NaN     0.0
      카페라떼   5000.0  5000  110.0  110  1000.0  1000.0
콜롬비아  아메리카노  4500.0  4500   10.0   10     NaN     0.0

In [56]:
# 그룹핑하여 인덱스가 사라짐.(reset_index() 필요)
df.groupby(['원산지', '칼로리']).mean(numeric_only=True)

               가격    이벤트가
원산지   칼로리
과테말라  110  5000.0     NaN
      250  5500.0  1000.0
대한민국  0    5300.0     NaN
코스타리카 20   3000.0     NaN
      110  5000.0  1000.0
      210  5900.0     NaN
콜롬비아  10   4500.0     NaN

In [57]:
# reset_index(): 그룹핑하여 인덱스가 사라진 상태에서 reset_index()를 사용하여 인덱스 생성
df.groupby(['원산지', '칼로리']).mean(numeric_only=True).reset_index()

     원산지  칼로리      가격    이벤트가
0   과테말라  110  5000.0     NaN
1   과테말라  250  5500.0  1000.0
2   대한민국    0  5300.0     NaN
3  코스타리카   20  3000.0     NaN
4  코스타리카  110  5000.0  1000.0
5  코스타리카  210  5900.0     NaN
6   콜롬비아   10  4500.0     NaN

In [58]:
df2 = pd.DataFrame({
    '과일' : ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리','딸기', '블루베리'],
    '가격' : [1000, None, 1500, None, 2000, 2500, None, 1800]

})

df2

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [59]:
# 과일의 그룹 수만큼 행이 줄어듬.
df2.groupby('과일').mean()

          가격
과일
딸기    1500.0
블루베리  2150.0

In [60]:
# transform(): 인자의 연산으로 집계는 하되, 원래 행마다 값을 붙여줌.
# 그룹 바이 후, 결측치를 계산에서 제외한 평균을 각 행마다 적어줌.(결측치가 있는 행에도 적어줌)
price = df2.groupby('과일')['가격'].transform("mean")
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [61]:
# fillna로 결측값만 채움
df2['가격'] = df2['가격'].fillna(price)
df2

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [62]:
df3 = pd.DataFrame({
    '과일' : ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리','딸기', '블루베리'],
    '등급' : ['B', 'B', 'A', 'A', 'A', 'A', 'B', 'B'],
    '가격' : [1000, None, 1500, None, 2000, 2500, None, 1800]
})

df3

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [63]:
# 예제3
price = df3.groupby(['과일', '등급'])['가격'].transform("mean")
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [64]:
# 예제3
df3['가격'] = df3['가격'].fillna(price)
df3

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0