In [1]:
# 런타임 > 세션 관리에서 기존 세션들을 끊어야 새로운 런타임 연결이 가능함.
# 좌측 파일 탭에서 업로드, 새로고침 버튼 오른쪽의 마운트 진행
import pandas as pd
%cd /content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

/content/drive/MyDrive/빅데이터분석기사_실기/Big-Data-Analysis-Engineer-Practical-Test/pandas

In [4]:
# 날짜와 시간 데이터
# 날짜는 하이픈(-)으로 연도-월-일 형태, 시간은 콜론(:)으로 시간:분:초 형태
# 슬래시(/)나 띄어쓰기( )로 주어질 수도 있음.
data ={
'Date1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
        # 콜론은 시간을 나타낼 때 사용하여 판다스가 인식하지 못함.(format = '%Y:%m:%d 필요)
'Date2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
        # 연도가 2자리라서 일/월/연도로 인식함. (format = '%y/%m/%d' 필요)
'Date3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
'Date4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
        #
'DateTime1': ['24-02-17 13:50:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
'DateTime2': ['2024-02-17 13-50-30', '2024-02-18 14-55-45', '2024-02-19 15-30-15','2024-02-20 16-10-50'],
'DateTime3': ['02/17/2024 01:50:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
'DateTime4': ['17 Feb 2024 13:50:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50']
}
df = pd.DataFrame(data)
df.to_csv("date_data.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:50:30,2024-02-17 13-50-30,02/17/2024 01:50:30 PM,17 Feb 2024 13:50:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14-55-45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15-30-15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16-10-50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [6]:
# 파이썬을 데이터를 불러올 때 날짜와 시간을 자동으로 인식하지 못함. 문자열로 인식해 object로 나옴.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [23]:
# to_datetime(df['컬럼명']): datetime 자료형
# 	Date1	      Date2	      Date3	    Date4	      Date5	      DateTime1	        DateTime2	          DateTime3	              DateTime4
#0	2024-02-17	2024:02:17	24/02/17	02/17/2024	17-Feb-2024	24-02-17 13:50:30	2024-02-17 13-50-30	02/17/2024 01:50:30 PM	17 Feb 2024 13:50:30
df = pd.read_csv("date_data.csv")
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'], format='%y/%m/%d')
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format='%y-%m-%d %H:%M:%S')
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
# 02/17/2024 01:50:30 PM / AM과 PM 있을 때는 %H 쓰면 틀림. %I + %p 활용
df['DateTime3'] = pd.to_datetime(df['DateTime3'], format='%m/%d/%Y %I:%M:%S %p')
# 17 Feb 2024 13:50:30
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024-02-17 13:50:30,2024-02-17 13:50:30,2024-02-17 13:50:30
1,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15
3,2024-02-20,2024-02-20,2024-02-20,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50

In [24]:
# datetime 형태로 변경되었음.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      datetime64[ns]
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      datetime64[ns]
 4   Date5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      datetime64[ns]
 8   DateTime4  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9)
memory usage: 420.0 bytes

In [26]:
# datetime 자료형만 dt를 사용할 수 있음.
df['year'] = df['DateTime1'].dt.year
df['month'] = df['DateTime1'].dt.month
df['day'] = df['DateTime1'].dt.day
df['hour'] = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,second
0,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024-02-17 13:50:30,2024-02-17 13:50:30,2024-02-17 13:50:30,2024,2,17,13,50,30
1,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024,2,18,14,55,45
2,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19,2024-02-19 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15,2024,2,19,15,30,15
3,2024-02-20,2024-02-20,2024-02-20,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50,2024,2,20,16,10,50

In [27]:
# dt.dayofweek: 요일을 숫자로 변경한 값 반환
# 0: 월요일 ... 6: 일요일
df['DateTime1'].dt.dayofweek

0    5
1    6
2    0
3    1
Name: DateTime1, dtype: int32

In [29]:
# 특정 시점과 특정 구간
print(df['DateTime1'].dt.to_period('Y')) # 연도
print(df['DateTime1'].dt.to_period('Q')) # 분기
print(df['DateTime1'].dt.to_period('M')) # 월
print(df['DateTime1'].dt.to_period('D')) # 일
print(df['DateTime1'].dt.to_period('H')) # 시간

0    2024
1    2024
2    2024
3    2024
Name: DateTime1, dtype: period[Y-DEC]
0    2024Q1
1    2024Q1
2    2024Q1
3    2024Q1
Name: DateTime1, dtype: period[Q-DEC]
0    2024-02
1    2024-02
2    2024-02
3    2024-02
Name: DateTime1, dtype: period[M]
0    2024-02-17
1    2024-02-18
2    2024-02-19
3    2024-02-20
Name: DateTime1, dtype: period[D]
0    2024-02-17 13:00
1    2024-02-18 14:00
2    2024-02-19 15:00
3    2024-02-20 16:00
Name: DateTime1, dtype: period[h]

/tmp/ipykernel_791/985440107.py:6: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  print(df['DateTime1'].dt.to_period('H'))